/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rent_a_Car;

import java.lang.UnsupportedOperationException;
import  java.lang.NoClassDefFoundError;
import static Rent_a_Car.Baglanti.kullanici_adi;
import static Rent_a_Car.Baglanti.parola;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bugra
 */
public class CarRental extends javax.swing.JFrame {
    
   DataBase islemler = new DataBase();
   DatabaseEkrani databaseekrani = new DatabaseEkrani();

    
    public CarRental() {
    initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        button_group = new javax.swing.ButtonGroup();
        button_group2 = new javax.swing.ButtonGroup();
        solpanel = new javax.swing.JPanel();
        baslik = new javax.swing.JLabel();
        surname = new javax.swing.JLabel();
        phonenumber = new javax.swing.JLabel();
        idnumber = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_surname = new javax.swing.JTextField();
        tf_phonenumber = new javax.swing.JTextField();
        tf_idnumber = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        confirm_butonu = new javax.swing.JButton();
        guncelle_butonu = new javax.swing.JButton();
        silme_butonu = new javax.swing.JButton();
        database_kaydet = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        logo_solpanel = new javax.swing.JLabel();
        radio_female = new javax.swing.JRadioButton();
        radio_male = new javax.swing.JRadioButton();
        sagpanel = new javax.swing.JPanel();
        baslik2 = new javax.swing.JLabel();
        marka = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        modelyili1 = new javax.swing.JLabel();
        combobrand = new javax.swing.JComboBox();
        combomodelyear = new javax.swing.JComboBox();
        tf_model = new javax.swing.JTextField();
        dailyprice = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        tf_dailyprice = new javax.swing.JTextField();
        tf_day = new javax.swing.JTextField();
        data_butonu = new javax.swing.JButton();
        radio_gasoline = new javax.swing.JRadioButton();
        radio_diesel = new javax.swing.JRadioButton();
        fueltype = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        logo_sagpanel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Baslik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        soru_isareti_logo = new javax.swing.JLabel();
        cikis_butonu = new javax.swing.JLabel();
        cerceve = new javax.swing.JLabel();
        arka_plan = new javax.swing.JLabel();

        setTitle("Rent a Car System");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(470, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(935, 850));
        setPreferredSize(new java.awt.Dimension(945, 880));
        setResizable(false);
        setSize(new java.awt.Dimension(945, 880));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Baslik, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solpanel.setBackground(new java.awt.Color(249, 249, 249));
        solpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), java.awt.Color.black));
        solpanel.setForeground(new java.awt.Color(255, 0, 0));
        solpanel.setAutoscrolls(true);
        solpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        solpanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        solpanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        solpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baslik.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        baslik.setForeground(new java.awt.Color(3, 60, 60));
        baslik.setText("USER INFORMATIONS");
        solpanel.add(baslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        surname.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        surname.setText("Surname            ");
        solpanel.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 80));

        phonenumber.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        phonenumber.setText("Phone Number  ");
        solpanel.add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 80));

        idnumber.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        idnumber.setText("ID Number        ");
        solpanel.add(idnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 80));

        name1.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        name1.setText("Name                 ");
        solpanel.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 80));

        tf_name.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        solpanel.add(tf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 150, -1));

        tf_surname.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        solpanel.add(tf_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, -1));

        tf_phonenumber.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        solpanel.add(tf_phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 150, -1));

        tf_idnumber.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        solpanel.add(tf_idnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 150, -1));

        mesaj_yazisi.setBackground(new java.awt.Color(255, 230, 235));
        mesaj_yazisi.setFont(new java.awt.Font("Eras Light ITC", 1, 15)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(204, 0, 0));
        solpanel.add(mesaj_yazisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 380, 20));

        confirm_butonu.setBackground(new java.awt.Color(0, 21, 21));
        confirm_butonu.setFont(new java.awt.Font("Eras Light ITC", 1, 17)); // NOI18N
        confirm_butonu.setForeground(new java.awt.Color(255, 255, 255));
        confirm_butonu.setText("CONFIRM");
        confirm_butonu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        confirm_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirm_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_butonuActionPerformed(evt);
            }
        });
        solpanel.add(confirm_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 30));

        guncelle_butonu.setBackground(new java.awt.Color(0, 21, 21));
        guncelle_butonu.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        guncelle_butonu.setForeground(new java.awt.Color(255, 255, 255));
        guncelle_butonu.setText("UPDATE");
        guncelle_butonu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        guncelle_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guncelle_butonu.setMaximumSize(new java.awt.Dimension(139, 37));
        guncelle_butonu.setMinimumSize(new java.awt.Dimension(139, 37));
        guncelle_butonu.setPreferredSize(new java.awt.Dimension(139, 37));
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonuActionPerformed(evt);
            }
        });
        solpanel.add(guncelle_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 110, 30));

        silme_butonu.setBackground(new java.awt.Color(0, 21, 21));
        silme_butonu.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        silme_butonu.setForeground(new java.awt.Color(255, 255, 255));
        silme_butonu.setText("DELETE");
        silme_butonu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        silme_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        silme_butonu.setMaximumSize(new java.awt.Dimension(139, 37));
        silme_butonu.setMinimumSize(new java.awt.Dimension(139, 37));
        silme_butonu.setPreferredSize(new java.awt.Dimension(139, 37));
        silme_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silme_butonuActionPerformed(evt);
            }
        });
        solpanel.add(silme_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, 30));

        database_kaydet.setBackground(new java.awt.Color(0, 21, 21));
        database_kaydet.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        database_kaydet.setForeground(new java.awt.Color(255, 255, 255));
        database_kaydet.setText("SAVE DB");
        database_kaydet.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        database_kaydet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        database_kaydet.setMaximumSize(new java.awt.Dimension(139, 37));
        database_kaydet.setMinimumSize(new java.awt.Dimension(139, 37));
        database_kaydet.setPreferredSize(new java.awt.Dimension(139, 37));
        database_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                database_kaydetActionPerformed(evt);
            }
        });
        solpanel.add(database_kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 110, 30));
        solpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 440, 10));
        solpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 440, 20));

        logo_solpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/rd_logo.png"))); // NOI18N
        solpanel.add(logo_solpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        button_group2.add(radio_female);
        radio_female.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        radio_female.setText("Female");
        radio_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_femaleActionPerformed(evt);
            }
        });
        solpanel.add(radio_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 50));

        button_group2.add(radio_male);
        radio_male.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        radio_male.setText("Male");
        solpanel.add(radio_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 100, 50));

        getContentPane().add(solpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 440, 520));

        sagpanel.setBackground(new java.awt.Color(249, 249, 249));
        sagpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), java.awt.Color.black));
        sagpanel.setForeground(new java.awt.Color(255, 0, 0));
        sagpanel.setAutoscrolls(true);
        sagpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sagpanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        sagpanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sagpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baslik2.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        baslik2.setForeground(new java.awt.Color(3, 60, 60));
        baslik2.setText("CAR INFORMATIONS");
        sagpanel.add(baslik2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 50));

        marka.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        marka.setText("Brand");
        sagpanel.add(marka, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 80));

        model.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        model.setText("Model");
        sagpanel.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 80));

        modelyili1.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        modelyili1.setText("Model Year");
        sagpanel.add(modelyili1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 90));

        combobrand.setBackground(new java.awt.Color(3, 86, 86));
        combobrand.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combobrand.setForeground(new java.awt.Color(255, 255, 255));
        combobrand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AUDI", "BMW", "CHEVROLET", "CITROEN", "FIAT", "FORD", "HONDA", "HYUNDAI", "KIA", "MERCEDES", "NISSAN", "OPEL", "PEUGEOT", "RENAULT", "SEAT", "SKODA", "TOYOTA", "VOLKSWAGEN", "VOLVO", "DAEWOO", "DAIHATSU", "GEELY", "DODGE", "CADILLAC", "LEXUS", "ISUZU", "JEEP", "SUZUKI", "MITSUBISHI", "PORSCHE", "LAND ROVER", "INFINITI", "MAZDA", "TOFAS", "ALFA ROMEO", "DACIA", "SSANGYONG" }));
        combobrand.setAlignmentX(0.3F);
        combobrand.setAlignmentY(0.3F);
        combobrand.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        combobrand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combobrand.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        combobrand.setPreferredSize(new java.awt.Dimension(70, 20));
        combobrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobrandActionPerformed(evt);
            }
        });
        sagpanel.add(combobrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, 30));

        combomodelyear.setBackground(new java.awt.Color(3, 86, 86));
        combomodelyear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combomodelyear.setForeground(new java.awt.Color(255, 255, 255));
        combomodelyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900", "1899", "1898", "1897", "1896", "1895", "1894", "1893", "1892", "1891", "1890", "1889", "1888", "1887", "1886", "1885", "1884", "1883", "1882", "1881", "1880", "1879", "1878", "1877", "1876", "1875", "1874", "1873", "1872", "1871", "1870", "1869", "1868", "1867", "1866", "1865", "1864", "1863", "1862", "1861", "1860", "1859", "1858", "1857", "1856", "1855", "1854", "1853", "1852", "1851", "1850" }));
        combomodelyear.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        combomodelyear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combomodelyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomodelyearActionPerformed(evt);
            }
        });
        sagpanel.add(combomodelyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, 30));

        tf_model.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tf_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_modelActionPerformed(evt);
            }
        });
        sagpanel.add(tf_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        dailyprice.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        dailyprice.setText("Daily Price ($)");
        sagpanel.add(dailyprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 90));

        day.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        day.setText("Day");
        sagpanel.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, 100));

        tf_dailyprice.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tf_dailyprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dailypriceActionPerformed(evt);
            }
        });
        sagpanel.add(tf_dailyprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 293, 170, -1));

        tf_day.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tf_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dayActionPerformed(evt);
            }
        });
        sagpanel.add(tf_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 170, -1));

        data_butonu.setBackground(new java.awt.Color(0, 21, 21));
        data_butonu.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        data_butonu.setForeground(new java.awt.Color(255, 255, 255));
        data_butonu.setText("SHOW THE DATABASE");
        data_butonu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        data_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data_butonu.setMaximumSize(new java.awt.Dimension(139, 37));
        data_butonu.setMinimumSize(new java.awt.Dimension(139, 37));
        data_butonu.setPreferredSize(new java.awt.Dimension(139, 37));
        data_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_butonuActionPerformed(evt);
            }
        });
        sagpanel.add(data_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 300, 50));

        button_group.add(radio_gasoline);
        radio_gasoline.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        radio_gasoline.setText("Gasoline");
        sagpanel.add(radio_gasoline, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 370, 100, 50));

        button_group.add(radio_diesel);
        radio_diesel.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        radio_diesel.setText("Diesel");
        radio_diesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_dieselActionPerformed(evt);
            }
        });
        sagpanel.add(radio_diesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 370, 80, 50));

        fueltype.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        fueltype.setText("Fuel Type");
        sagpanel.add(fueltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 50));
        sagpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 258, 440, -1));
        sagpanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 440, 10));

        logo_sagpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/rd_logo.png"))); // NOI18N
        sagpanel.add(logo_sagpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, -1, -1));

        getContentPane().add(sagpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 440, 520));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Baslik.setBackground(new java.awt.Color(249, 249, 249));
        Baslik.setFont(new java.awt.Font("Eras Light ITC", 1, 44)); // NOI18N
        Baslik.setForeground(new java.awt.Color(0, 102, 102));
        Baslik.setText("Rent a Car System");
        jPanel1.add(Baslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 370, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 390, 60));

        urun_tablosu.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        urun_tablosu.setForeground(new java.awt.Color(0, 102, 102));
        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Surname", "Gender", "Phone Number", "ID Number", "Brand", "Model", "Model Year", "Daily Price", "Day", "Fuel Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        urun_tablosu.setGridColor(new java.awt.Color(0, 153, 153));
        urun_tablosu.setSelectionBackground(new java.awt.Color(0, 153, 153));
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);
        if (urun_tablosu.getColumnModel().getColumnCount() > 0) {
            urun_tablosu.getColumnModel().getColumn(0).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(1).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(2).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(3).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(4).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(5).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(6).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(7).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(8).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(9).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(10).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 900, 240));

        soru_isareti_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/soru_isareti.png"))); // NOI18N
        soru_isareti_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        soru_isareti_logo.setMinimumSize(new java.awt.Dimension(25, 25));
        soru_isareti_logo.setName(""); // NOI18N
        soru_isareti_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soru_isareti_logoMouseClicked(evt);
            }
        });
        getContentPane().add(soru_isareti_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 40));

        cikis_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/exit_logo_2.png"))); // NOI18N
        cikis_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cikis_butonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikis_butonuMouseClicked(evt);
            }
        });
        getContentPane().add(cikis_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 40));

        cerceve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/cerceve.png"))); // NOI18N
        getContentPane().add(cerceve, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        arka_plan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/beyaz.jpg"))); // NOI18N
        getContentPane().add(arka_plan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -6, 970, 910));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobrandActionPerformed

    private void combomodelyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomodelyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combomodelyearActionPerformed

    private void tf_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dayActionPerformed

    private void tf_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_modelActionPerformed

    private void tf_dailypriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dailypriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dailypriceActionPerformed

    private void confirm_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_butonuActionPerformed
     
     mesaj_yazisi.setText("");
    
     String yakit = "";
     if(radio_diesel.isSelected()){
         yakit = "Diesel";
     }
     if(radio_gasoline.isSelected()){
         yakit = "Gasoline";
     }
     
     String cinsiyet = "";
     if(radio_male.isSelected()){
         cinsiyet = "Male";
     }
     if(radio_female.isSelected()){
         cinsiyet = "Female";
     }
     
     DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
     if ( tf_name.getText().trim().equals("") || tf_surname.getText().trim().equals("") || cinsiyet.trim().equals("") || tf_phonenumber.getText().trim().equals("") || tf_idnumber.getText().trim().equals("") || tf_model.getText().trim().equals("") || tf_dailyprice.getText().trim().equals("") || tf_day.getText().trim().equals("") || yakit.trim().equals("") ){
         mesaj_yazisi.setText("                            Please Fill All the Blanks !");
     }
     else {
         Object[] eklenecek = {tf_name.getText(),tf_surname.getText(),cinsiyet,tf_phonenumber.getText(),tf_idnumber.getText(),combobrand.getSelectedItem().toString(),tf_model.getText(),combomodelyear.getSelectedItem().toString(),tf_dailyprice.getText(),tf_day.getText(),yakit};
         model.addRow(eklenecek);
     }
 
    }//GEN-LAST:event_confirm_butonuActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonuActionPerformed
        mesaj_yazisi.setText("");
       
        String yakit = "";
        if(radio_gasoline.isSelected()){
            yakit = "Gasoline";
        }
        if(radio_diesel.isSelected()){
            yakit = "Diesel";
        }
        
        String cinsiyet = "";
        if(radio_male.isSelected()){
         cinsiyet = "Male";
         }
        if(radio_female.isSelected()){
        cinsiyet = "Female";
        }
        
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        int secili_row  = urun_tablosu.getSelectedRow();
        if ( secili_row == -1 ) {
            if (urun_tablosu.getRowCount() == 0 ) {
                mesaj_yazisi.setText("                                 The Table is Empty !");
            } else {
                mesaj_yazisi.setText("Please Choose the Line That You Want to UPDATE !");
            }
        } 
        else {
            model.setValueAt(tf_name.getText(),secili_row,0);
            model.setValueAt(tf_surname.getText(),secili_row,1);
            model.setValueAt(cinsiyet,secili_row,2);
            model.setValueAt(tf_phonenumber.getText(),secili_row,3);
            model.setValueAt(tf_idnumber.getText(),secili_row,4);
            model.setValueAt(combobrand.getSelectedItem().toString(),secili_row,5);
            model.setValueAt(tf_model.getText(),secili_row,6);
            model.setValueAt(combomodelyear.getSelectedItem().toString(),secili_row,7);
            model.setValueAt(tf_dailyprice.getText(),secili_row,8);
            model.setValueAt(tf_day.getText(),secili_row,9);
            model.setValueAt(yakit,secili_row,10);
            
            mesaj_yazisi.setText("                          Line UPDATED Successfully !");
        }
        
    }//GEN-LAST:event_guncelle_butonuActionPerformed


    private void silme_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silme_butonuActionPerformed
       
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        int secili_row  = urun_tablosu.getSelectedRow();
        if ( secili_row == -1 ) {
            if (urun_tablosu.getRowCount() == 0 ) {
                mesaj_yazisi.setText("                                 The Table is Empty !");
            } else {
                mesaj_yazisi.setText("Please Choose the Line That You Want to DELETE !");
            }
        } 
        else {
            model.removeRow(secili_row);
            mesaj_yazisi.setText("                          Line DELETED Successfully !");
        }
    }//GEN-LAST:event_silme_butonuActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
 
       DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
       int secili_row = urun_tablosu.getSelectedRow();
       
       tf_name.setText(model.getValueAt(secili_row,0).toString());
       tf_surname.setText(model.getValueAt(secili_row,1).toString());
       tf_phonenumber.setText(model.getValueAt(secili_row,3).toString());
       tf_idnumber.setText(model.getValueAt(secili_row,4).toString());
       combobrand.setSelectedItem(model.getValueAt(secili_row,5).toString());
       tf_model.setText(model.getValueAt(secili_row,6).toString());
       combomodelyear.setSelectedItem(model.getValueAt(secili_row,7).toString());
       tf_dailyprice.setText(model.getValueAt(secili_row,8).toString());
       tf_day.setText(model.getValueAt(secili_row,9).toString());
       
       
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void data_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_butonuActionPerformed
        
       DatabaseEkrani database_ekrani = new DatabaseEkrani(this,true);
       database_ekrani.setVisible(true);
       
       
        
    }//GEN-LAST:event_data_butonuActionPerformed

    private void database_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_database_kaydetActionPerformed
       
        String yakit = "";
        if(radio_gasoline.isSelected()){
            yakit = "Gasoline";
        }
        if(radio_diesel.isSelected()){
            yakit = "Diesel";
        }
        
        String cinsiyet = "";
        if(radio_male.isSelected()){
            cinsiyet = "Male";
        }
        if(radio_female.isSelected()){
            cinsiyet = "Female";
        }
        
        String name = tf_name.getText();
        String surname = tf_surname.getText();
        String phone_number = tf_phonenumber.getText();
        String id_number = tf_idnumber.getText();
        String brand = combobrand.getSelectedItem().toString();
        String model = tf_model.getText();
        String model_year = combomodelyear.getSelectedItem().toString();
        String daily_price = tf_dailyprice.getText();
        String day = tf_day.getText();
        
        
      if ( tf_name.getText().trim().equals("") || tf_surname.getText().trim().equals("") ||cinsiyet.trim().equals("")|| tf_phonenumber.getText().trim().equals("") || tf_idnumber.getText().trim().equals("") || tf_model.getText().trim().equals("") || tf_dailyprice.getText().trim().equals("") || tf_day.getText().trim().equals("") || yakit.trim().equals("") ) {
         
            mesaj_yazisi.setText("             Please Choose One Line from The Table !");
        }
      else {
        islemler.MusteriEkle(name,surname,cinsiyet,phone_number,id_number,brand,model,model_year,daily_price,day,yakit);
        mesaj_yazisi.setText("                    The Informations Saved to Database !");
        }
    }//GEN-LAST:event_database_kaydetActionPerformed

    private void radio_dieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_dieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_dieselActionPerformed

    private void cikis_butonuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikis_butonuMouseClicked
        
        int cikis = JOptionPane.showConfirmDialog(null,"Do You Want to Close the System ?","Exit",JOptionPane.YES_NO_OPTION);
        if (cikis == JOptionPane.YES_NO_OPTION){
            setVisible(false);
        }
    }//GEN-LAST:event_cikis_butonuMouseClicked

    private void radio_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_femaleActionPerformed

    private void soru_isareti_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soru_isareti_logoMouseClicked
     
     
        JOptionPane.showMessageDialog(null, "Coders : Buğra ATEŞ - Batuhan ERÇETİN \n                               Mentors :\nAssoc. Prof Dr. Taner ÇEVİK - RA. Çağdaş ÖZER");
    }//GEN-LAST:event_soru_isareti_logoMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baslik;
    private javax.swing.JLabel arka_plan;
    private javax.swing.JLabel baslik;
    private javax.swing.JLabel baslik2;
    private javax.swing.ButtonGroup button_group;
    private javax.swing.ButtonGroup button_group2;
    private javax.swing.JLabel cerceve;
    private javax.swing.JLabel cikis_butonu;
    private javax.swing.JComboBox combobrand;
    private javax.swing.JComboBox combomodelyear;
    private javax.swing.JButton confirm_butonu;
    private javax.swing.JLabel dailyprice;
    private javax.swing.JButton data_butonu;
    private javax.swing.JButton database_kaydet;
    private javax.swing.JLabel day;
    private javax.swing.JLabel fueltype;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel idnumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo_sagpanel;
    private javax.swing.JLabel logo_solpanel;
    private javax.swing.JLabel marka;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JLabel model;
    private javax.swing.JLabel modelyili1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel phonenumber;
    private javax.swing.JRadioButton radio_diesel;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_gasoline;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JPanel sagpanel;
    private javax.swing.JButton silme_butonu;
    private javax.swing.JPanel solpanel;
    private javax.swing.JLabel soru_isareti_logo;
    private javax.swing.JLabel surname;
    private javax.swing.JTextField tf_dailyprice;
    private javax.swing.JTextField tf_day;
    private javax.swing.JTextField tf_idnumber;
    private javax.swing.JTextField tf_model;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_phonenumber;
    private javax.swing.JTextField tf_surname;
    private javax.swing.JTable urun_tablosu;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
