/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rent_a_Car;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bugra
 */
public class KayitEkrani extends javax.swing.JFrame {
    SignupLogin signuplogin = new SignupLogin();

    /**
     * Creates new form KayitEkrani
     */
    public KayitEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        cikis_butonu = new javax.swing.JLabel();
        kayit_butonu2 = new javax.swing.JButton();
        tf_username2 = new javax.swing.JTextField();
        pf_password2 = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        cerceve = new javax.swing.JLabel();
        yesil2 = new javax.swing.JLabel();

        setTitle("Register");
        setBackground(new java.awt.Color(51, 51, 0));
        setBounds(new java.awt.Rectangle(600, 300, 0, 0));
        setForeground(new java.awt.Color(51, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, username, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cikis_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/cikis_logo.png"))); // NOI18N
        cikis_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cikis_butonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikis_butonuMouseClicked(evt);
            }
        });
        getContentPane().add(cikis_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        kayit_butonu2.setBackground(new java.awt.Color(0, 21, 21));
        kayit_butonu2.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        kayit_butonu2.setForeground(new java.awt.Color(255, 255, 255));
        kayit_butonu2.setText("SIGN UP");
        kayit_butonu2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        kayit_butonu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kayit_butonu2.setMinimumSize(new java.awt.Dimension(91, 29));
        kayit_butonu2.setPreferredSize(new java.awt.Dimension(91, 29));
        kayit_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_butonu2ActionPerformed(evt);
            }
        });
        getContentPane().add(kayit_butonu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 120, 40));

        tf_username2.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        tf_username2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_username2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 150, 30));

        pf_password2.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        pf_password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_password2ActionPerformed(evt);
            }
        });
        getContentPane().add(pf_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 150, 30));

        password.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, 30));

        username.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        username.setText("Username");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        cerceve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/kayitgiris_cerceve.png"))); // NOI18N
        getContentPane().add(cerceve, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        yesil2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/yesil2.png"))); // NOI18N
        getContentPane().add(yesil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -120, 860, 700));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_username2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_username2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_username2ActionPerformed

    private void pf_password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_password2ActionPerformed

    private void kayit_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_butonu2ActionPerformed
      
        String kayit_ad = tf_username2.getText();
        String kayit_sifre = String.valueOf(pf_password2.getPassword());
        if(kayit_ad.equals("") && kayit_sifre.equals("")) {
            
           JOptionPane.showMessageDialog(null, "Please Enter Username and Password !");
        }
        else if (kayit_ad.equals("")) {
            
            JOptionPane.showMessageDialog(null, "Please Enter a Username !");
     
        }
        else if (kayit_sifre.equals("")) {
            
            JOptionPane.showMessageDialog(null, "Please Enter a Password !");
            
        } else {
        
        PreparedStatement ps ;
        String sorgula = "INSERT INTO `uyelik_bilgileri`(`username`, `password`) VALUES (?,?)";
        try {
            ps = MyConnection.getConnection().prepareStatement(sorgula);
            ps.setString(1, kayit_ad);
            ps.setString(2, kayit_sifre);
            
            if ( ps.executeUpdate() > 0 ) {
                
                JOptionPane.showMessageDialog(null,"Account Registered Successfully !");
                 setVisible(false);
                
            }
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null,"This Username Already Exist !");
            
        }
        }
   
    }//GEN-LAST:event_kayit_butonu2ActionPerformed

    private void cikis_butonuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikis_butonuMouseClicked
       
        setVisible(false);
    }//GEN-LAST:event_cikis_butonuMouseClicked

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerceve;
    private javax.swing.JLabel cikis_butonu;
    private javax.swing.JButton kayit_butonu2;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField pf_password2;
    private javax.swing.JTextField tf_username2;
    private javax.swing.JLabel username;
    private javax.swing.JLabel yesil2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
