/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rent_a_Car;

import java.lang.UnsupportedOperationException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bugra
 */
class User {
    private String kullanici_adi ;
    private String parola ;
    
    public User(String kullanici_adi, String parola) {
        this.kullanici_adi = kullanici_adi;
        this.parola = parola;
    }

    public void setKullanici_adi(String kullanici_adi) {
        this.kullanici_adi = kullanici_adi;
    }

    public void setParola(String parola) {
        this.parola = parola;
    }

    public String getKullanici_adi() {
        return kullanici_adi;
    }

    public String getParola() {
        return parola;
    }
}

public class SignupLogin extends javax.swing.JFrame {
    
    DataBase islemler = new DataBase();
            
    
    private static ArrayList<User> user_list = new ArrayList<User>();

    public static ArrayList<User> getUser_list() {
        return user_list;
    }

    public static void setUser_list(ArrayList<User> user_list) {
        SignupLogin.user_list = user_list;
    }

    /**
     * Creates new form SignupLogin
     */
    public SignupLogin() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        cikis_butonu = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        kayit_butonu = new javax.swing.JButton();
        giris_butonu = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        cerceve = new javax.swing.JLabel();
        yesil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register / Login ");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(600, 300, 0, 0));
        setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, username, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cikis_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/cikis_logo.png"))); // NOI18N
        cikis_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cikis_butonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikis_butonuMouseClicked(evt);
            }
        });
        getContentPane().add(cikis_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        tf_username.setFont(new java.awt.Font("Eras Medium ITC", 1, 17)); // NOI18N
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 72, 138, -1));

        pf_password.setFont(new java.awt.Font("Eras Medium ITC", 1, 17)); // NOI18N
        pf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 144, 138, -1));

        kayit_butonu.setBackground(new java.awt.Color(0, 21, 21));
        kayit_butonu.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        kayit_butonu.setForeground(new java.awt.Color(255, 255, 255));
        kayit_butonu.setText("SIGN UP");
        kayit_butonu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        kayit_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kayit_butonu.setMaximumSize(new java.awt.Dimension(91, 29));
        kayit_butonu.setName(""); // NOI18N
        kayit_butonu.setPreferredSize(new java.awt.Dimension(91, 29));
        kayit_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_butonuActionPerformed(evt);
            }
        });
        getContentPane().add(kayit_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 100, 30));

        giris_butonu.setBackground(new java.awt.Color(0, 21, 21));
        giris_butonu.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        giris_butonu.setForeground(new java.awt.Color(255, 255, 255));
        giris_butonu.setText("SIGN IN");
        giris_butonu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        giris_butonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giris_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_butonuActionPerformed(evt);
            }
        });
        giris_butonu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                giris_butonuKeyPressed(evt);
            }
        });
        getContentPane().add(giris_butonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, 30));

        mesaj_yazisi.setBackground(new java.awt.Color(255, 230, 235));
        mesaj_yazisi.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(mesaj_yazisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 180, 30));

        password.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 105, 90, 40));

        username.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        username.setText("Username");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 30, 90, 40));

        cerceve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/kayitgiris_cerceve.png"))); // NOI18N
        getContentPane().add(cerceve, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        yesil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent_a_Car/yesil.png"))); // NOI18N
        getContentPane().add(yesil, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -120, 890, 700));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giris_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_butonuActionPerformed

    
    String kullanici_adi = tf_username.getText();
    String parola = new String(pf_password.getPassword());
    SignupLogin signuplogin = new SignupLogin();
    
    boolean girisbasarili = islemler.girisYap(kullanici_adi,parola);
    
    if(girisbasarili && !kullanici_adi.equals("") && !parola.equals("")){
        
        mesaj_yazisi.setText("  Login Successful !");
        JOptionPane.showMessageDialog(null,"Welcome "+kullanici_adi+" !");
        signuplogin.setVisible(false);
        CarRental carrental = new CarRental();
        carrental.setVisible(true);
 
    } else {
        mesaj_yazisi.setText("Login Unsuccessful !");
    }

    }//GEN-LAST:event_giris_butonuActionPerformed

    private void kayit_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_butonuActionPerformed
       KayitEkrani kayitekrani = new KayitEkrani();
       kayitekrani.setVisible(true);
      
    }//GEN-LAST:event_kayit_butonuActionPerformed

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void pf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_passwordActionPerformed

    private void giris_butonuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_giris_butonuKeyPressed
 
    }//GEN-LAST:event_giris_butonuKeyPressed

    private void cikis_butonuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikis_butonuMouseClicked

        int cikis = JOptionPane.showConfirmDialog(null,"Do You Want to Exit ?","Exit",JOptionPane.YES_NO_OPTION);
        if (cikis == JOptionPane.YES_NO_OPTION){
            
            String kullanici_adi = tf_username.getText();
            JOptionPane.showMessageDialog(null, "See You Later "+kullanici_adi+" !");
            System.exit(0);
        }
    }//GEN-LAST:event_cikis_butonuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Baglanti baglanti = new Baglanti();
        SignupLogin signup_login = new SignupLogin();     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerceve;
    private javax.swing.JLabel cikis_butonu;
    private javax.swing.JButton giris_butonu;
    private javax.swing.JButton kayit_butonu;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_username;
    private javax.swing.JLabel username;
    private javax.swing.JLabel yesil;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
